#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Navigate to the subdirectory and run lint-staged
cd apps/typing-app && npx lint-staged

# Verify TypeScript files in subdirectories
cd ../../
npx tsc --build apps/typing-app/tsconfig.json
